/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SelectOrgRouteImport } from './routes/select-org'
import { Route as AuthedOrgSlugRouteImport } from './routes/_authed/$orgSlug'
import { Route as AuthedOrgSlugIndexRouteImport } from './routes/_authed/$orgSlug/index'
import { Route as AuthedOrgSlugAuditRouteImport } from './routes/_authed/$orgSlug/audit'
import { Route as AuthedOrgSlugIssuesRouteImport } from './routes/_authed/$orgSlug/issues'
import { Route as AuthedOrgSlugMembersRouteImport } from './routes/_authed/$orgSlug/members'
import { Route as AuthedOrgSlugSettingsRouteImport } from './routes/_authed/$orgSlug/settings'
import { Route as AuthedOrgSlugProjectsIndexRouteImport } from './routes/_authed/$orgSlug/projects/index'
import { Route as AuthedOrgSlugProjectsProjectIdRouteImport } from './routes/_authed/$orgSlug/projects/$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectOrgRoute = SelectOrgRouteImport.update({
  id: '/select-org',
  path: '/select-org',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOrgSlugRoute = AuthedOrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgSlugIndexRoute = AuthedOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOrgSlugRoute,
} as any)
const AuthedOrgSlugAuditRoute = AuthedOrgSlugAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedOrgSlugRoute,
} as any)
const AuthedOrgSlugIssuesRoute = AuthedOrgSlugIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AuthedOrgSlugRoute,
} as any)
const AuthedOrgSlugMembersRoute = AuthedOrgSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedOrgSlugRoute,
} as any)
const AuthedOrgSlugSettingsRoute = AuthedOrgSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedOrgSlugRoute,
} as any)
const AuthedOrgSlugProjectsIndexRoute =
  AuthedOrgSlugProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthedOrgSlugRoute,
  } as any)
const AuthedOrgSlugProjectsProjectIdRoute =
  AuthedOrgSlugProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthedOrgSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/select-org': typeof SelectOrgRoute
  '/$orgSlug': typeof AuthedOrgSlugRouteWithChildren
  '/$orgSlug/audit': typeof AuthedOrgSlugAuditRoute
  '/$orgSlug/issues': typeof AuthedOrgSlugIssuesRoute
  '/$orgSlug/members': typeof AuthedOrgSlugMembersRoute
  '/$orgSlug/settings': typeof AuthedOrgSlugSettingsRoute
  '/$orgSlug/': typeof AuthedOrgSlugIndexRoute
  '/$orgSlug/projects/$projectId': typeof AuthedOrgSlugProjectsProjectIdRoute
  '/$orgSlug/projects/': typeof AuthedOrgSlugProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/select-org': typeof SelectOrgRoute
  '/$orgSlug/audit': typeof AuthedOrgSlugAuditRoute
  '/$orgSlug/issues': typeof AuthedOrgSlugIssuesRoute
  '/$orgSlug/members': typeof AuthedOrgSlugMembersRoute
  '/$orgSlug/settings': typeof AuthedOrgSlugSettingsRoute
  '/$orgSlug': typeof AuthedOrgSlugIndexRoute
  '/$orgSlug/projects/$projectId': typeof AuthedOrgSlugProjectsProjectIdRoute
  '/$orgSlug/projects': typeof AuthedOrgSlugProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/select-org': typeof SelectOrgRoute
  '/_authed/$orgSlug': typeof AuthedOrgSlugRouteWithChildren
  '/_authed/$orgSlug/audit': typeof AuthedOrgSlugAuditRoute
  '/_authed/$orgSlug/issues': typeof AuthedOrgSlugIssuesRoute
  '/_authed/$orgSlug/members': typeof AuthedOrgSlugMembersRoute
  '/_authed/$orgSlug/settings': typeof AuthedOrgSlugSettingsRoute
  '/_authed/$orgSlug/': typeof AuthedOrgSlugIndexRoute
  '/_authed/$orgSlug/projects/$projectId': typeof AuthedOrgSlugProjectsProjectIdRoute
  '/_authed/$orgSlug/projects/': typeof AuthedOrgSlugProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/select-org'
    | '/$orgSlug'
    | '/$orgSlug/audit'
    | '/$orgSlug/issues'
    | '/$orgSlug/members'
    | '/$orgSlug/settings'
    | '/$orgSlug/'
    | '/$orgSlug/projects/$projectId'
    | '/$orgSlug/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/select-org'
    | '/$orgSlug/audit'
    | '/$orgSlug/issues'
    | '/$orgSlug/members'
    | '/$orgSlug/settings'
    | '/$orgSlug'
    | '/$orgSlug/projects/$projectId'
    | '/$orgSlug/projects'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/select-org'
    | '/_authed/$orgSlug'
    | '/_authed/$orgSlug/audit'
    | '/_authed/$orgSlug/issues'
    | '/_authed/$orgSlug/members'
    | '/_authed/$orgSlug/settings'
    | '/_authed/$orgSlug/'
    | '/_authed/$orgSlug/projects/$projectId'
    | '/_authed/$orgSlug/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SelectOrgRoute: typeof SelectOrgRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-org': {
      id: '/select-org'
      path: '/select-org'
      fullPath: '/select-org'
      preLoaderRoute: typeof SelectOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/$orgSlug': {
      id: '/_authed/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof AuthedOrgSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$orgSlug/': {
      id: '/_authed/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof AuthedOrgSlugIndexRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
    '/_authed/$orgSlug/audit': {
      id: '/_authed/$orgSlug/audit'
      path: '/audit'
      fullPath: '/$orgSlug/audit'
      preLoaderRoute: typeof AuthedOrgSlugAuditRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
    '/_authed/$orgSlug/issues': {
      id: '/_authed/$orgSlug/issues'
      path: '/issues'
      fullPath: '/$orgSlug/issues'
      preLoaderRoute: typeof AuthedOrgSlugIssuesRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
    '/_authed/$orgSlug/members': {
      id: '/_authed/$orgSlug/members'
      path: '/members'
      fullPath: '/$orgSlug/members'
      preLoaderRoute: typeof AuthedOrgSlugMembersRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
    '/_authed/$orgSlug/settings': {
      id: '/_authed/$orgSlug/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof AuthedOrgSlugSettingsRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
    '/_authed/$orgSlug/projects/': {
      id: '/_authed/$orgSlug/projects/'
      path: '/projects'
      fullPath: '/$orgSlug/projects/'
      preLoaderRoute: typeof AuthedOrgSlugProjectsIndexRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
    '/_authed/$orgSlug/projects/$projectId': {
      id: '/_authed/$orgSlug/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/$orgSlug/projects/$projectId'
      preLoaderRoute: typeof AuthedOrgSlugProjectsProjectIdRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
  }
}

interface AuthedOrgSlugRouteChildren {
  AuthedOrgSlugAuditRoute: typeof AuthedOrgSlugAuditRoute
  AuthedOrgSlugIssuesRoute: typeof AuthedOrgSlugIssuesRoute
  AuthedOrgSlugMembersRoute: typeof AuthedOrgSlugMembersRoute
  AuthedOrgSlugSettingsRoute: typeof AuthedOrgSlugSettingsRoute
  AuthedOrgSlugIndexRoute: typeof AuthedOrgSlugIndexRoute
  AuthedOrgSlugProjectsProjectIdRoute: typeof AuthedOrgSlugProjectsProjectIdRoute
  AuthedOrgSlugProjectsIndexRoute: typeof AuthedOrgSlugProjectsIndexRoute
}

const AuthedOrgSlugRouteChildren: AuthedOrgSlugRouteChildren = {
  AuthedOrgSlugAuditRoute: AuthedOrgSlugAuditRoute,
  AuthedOrgSlugIssuesRoute: AuthedOrgSlugIssuesRoute,
  AuthedOrgSlugMembersRoute: AuthedOrgSlugMembersRoute,
  AuthedOrgSlugSettingsRoute: AuthedOrgSlugSettingsRoute,
  AuthedOrgSlugIndexRoute: AuthedOrgSlugIndexRoute,
  AuthedOrgSlugProjectsProjectIdRoute: AuthedOrgSlugProjectsProjectIdRoute,
  AuthedOrgSlugProjectsIndexRoute: AuthedOrgSlugProjectsIndexRoute,
}

const AuthedOrgSlugRouteWithChildren = AuthedOrgSlugRoute._addFileChildren(
  AuthedOrgSlugRouteChildren,
)

interface AuthedRouteChildren {
  AuthedOrgSlugRoute: typeof AuthedOrgSlugRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOrgSlugRoute: AuthedOrgSlugRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SelectOrgRoute: SelectOrgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
